# Generated by Django 6.0 on 2026-05-28 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_task_options_task_order_task_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
